steps:
  - id: prepare-reference-ready-game-unity
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        # No need to unzip at this stage. Will md5 this zip and create one in storage
        # Then add this directly to complete-client-unity
        gsutil cp gs://${_GCS_BUCKET}/references.zip /tmp/references.zip
        md5=$(md5sum "/tmp/references.zip" | cut -d ' ' -f 1) && echo $md5 >> "references-checksum" && mv "/tmp/references.zip" "/workspace/$md5.zip"
        # Add -n parameter to gsutil cp so that it can skip if there is one with the same name already
        md5=$(cat "references-checksum") && gsutil cp -n "/workspace/$md5.zip" "gs://${_GCS_BUCKET}/references-$md5.zip"

        #
        mkdir game-unity
        # Move related folders and files to this folder
        mv /workspace/complete-client-unity /workspace/game-unity/
        mv /workspace/game-specific /workspace/game-unity/
        mv /workspace/prepare-ucb-build-release /workspace/game-unity/

        # md5=$(cat "references-checksum") && mv "/workspace/$md5.zip" "/workspace/game-unity/complete-client-unity/references.zip"
        mv "references-checksum" "/workspace/game-unity/complete-client-unity/"
        # Need to retrieve preprocessed-assets.zip and place it in complete-client-unity as well
        # md5=$(cat "/workspace/game-unity/game-specific/preprocessed-assets-checksum") && gsutil cp "gs://${_GCS_BUCKET}/preprocessed-assets-$md5.zip" "/workspace/game-unity/complete-client-unity/preprocessed-assets.zip"
        mv "/workspace/game-unity/game-specific/preprocessed-assets-checksum" "/workspace/game-unity/complete-client-unity/"

        mv /workspace/unity-setup /workspace/game-unity/
        mv /workspace/.gitattributes /workspace/game-unity/
        mv /workspace/.gitignore /workspace/game-unity/
        mv /workspace/remove-dsstore.ps1 /workspace/game-unity/
        mv /workspace/setup-game-ref.ps1 /workspace/game-unity/

  - id: organize-prepared-complete-client-project
    name: "mcr.microsoft.com/powershell:preview-alpine-3.10"
    entrypoint: sh
    args:
      - -c
      - |
        # Enter into game-unity folder
        cd /workspace/game-unity
        # Execute powershell scripts

        # pwsh remove-dsstore.ps1
        pwsh ./prepare-ucb-build-release/CopyNecessaryItem.ps1

        # Need to change this work to that the setup is moving files rather than current json
        # Add bash file to instruct where preprocessed-assets is moved to, can actually generate here
        cd /workspace/game-unity/unity-setup
        pwsh FileMoveCompleteReferences.ps1
        mv /workspace/game-unity/move-files.sh /workspace/game-unity/complete-client-unity

        mv /workspace/game-unity/game-specific /workspace/game-unity/complete-client-unity

  - id: retrieve-ssh-key
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=rayjb_google_rsa > /root/.ssh/rayjb_google_rsa' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - id: commit-ucb-build-release
    # name: gcr.io/cloud-builders/gcloud
    name: "alpine:latest"
    entrypoint: sh
    args:
      - -c
      - |

        apk update && apk add git git-lfs openssh-client rsync

        chmod 600 /root/.ssh/rayjb_google_rsa

        eval `ssh-agent -s`
        ssh-add /root/.ssh/rayjb_google_rsa

        touch /root/.ssh/known_hosts
        ssh-keyscan -p 2022 source.developers.google.com >> /root/.ssh/known_hosts

        git clone ssh://ray@joybrick.cc@source.developers.google.com:2022/p/wander-around-io/r/ucb-build-release

        cd ucb-build-release
        # git remote add from-repo ssh://ray@joybrick.cc@source.developers.google.com:2022/p/wander-around-io/r/github_ray-joybrick_walkio
        git remote add from-repo ssh://ray@joybrick.cc@source.developers.google.com:2022/p/wander-around-io/r/github_ray-joybrick_wander-around-io-build-release

        git config --local user.email "ray@joybrick.cc"
        git config --local user.name "Ray Wang"

        git fetch --all

        git show-ref

        # git checkout -b ucb-build-release
        git reset --hard from-repo/prepare-build-release

        rsync -avhr --exclude '.git' --delete /workspace/game-unity/complete-client-client-unity/ /workspace/ucb-build-release/

        rm /workspace/ucb-build-release/.gitattributes
        rm /workspace/ucb-build-release/.gitignore

        git add .
        git commit -m "Commit from auto build"

        git push origin master --force

        # git push origin ucb-build-release --force
        # git push origin ucb-build-release

    volumes:
      - name: 'ssh'
        path: /root/.ssh
    
