# Stage 1
FROM mcr.microsoft.com/powershell:lts-alpine-3.10 as call-api

ARG ORG_ID
ARG API_KEY
ARG PROJECT_ID
ARG JSON_FILE_PATH
# ARG JSON_DATA

COPY ./development-support/setup-unity-cloud-build/${JSON_FILE_PATH} ${JSON_FILE_PATH}
COPY ./development-support/setup-unity-cloud-build/create-build-target.ps1 create-build-target.ps1

RUN pwsh create-build-target.ps1 -apiKey ${API_KEY} -orgId ${ORG_ID} -projectId ${PROJECT_ID} -sourceFilePath ${JSON_FILE_PATH}
