# Stage 1
FROM mcr.microsoft.com/powershell:lts-alpine-3.10 as call-api

ARG ORG_ID
ARG API_KEY
ARG PROJECT_ID
# ARG JSON_DATA

COPY ./dev-setup-unity-cloud-build/create-project-make-asset-build-target.json update-project-make-asset-build-target.json
COPY ./dev-setup-unity-cloud-build/update-project-make-asset-build-target.ps1 update-project-make-asset-build-target.ps1

RUN pwsh update-project-make-asset-build-target.ps1 -apiKey ${API_KEY} -orgId ${ORG_ID} -projectId ${PROJECT_ID}
