# Stage 1
FROM mcr.microsoft.com/powershell:lts-alpine-3.10 as call-api

ARG ORG_ID
ARG API_KEY
ARG JSON_FILE_PATH

COPY ./development-support/setup-unity-cloud-build/${JSON_FILE_PATH} ${JSON_FILE_PATH}
COPY ./development-support/setup-unity-cloud-build/create-project.ps1 create-project.ps1

RUN pwsh create-project.ps1 -apiKey ${API_KEY} -orgId ${ORG_ID} -sourceFilePath ${JSON_FILE_PATH}
